# Physical properties
mass: 20.0                          # Mass in kg
inertia:
  ixx: 1.2                          # Moment of inertia around x-axis
  iyy: 1.2                          # Moment of inertia around y-axis
  izz: 2.5                          # Moment of inertia around z-axis

# Environmental conditions
buoyancy_offset: 5.0                # Buoyancy in Newtons (to maintain neutral buoyancy)
drag_coefficients:
  x: 0.8
  y: 0.8
  z: 1.0

# Inaccuracies
loc_inacc: 0
IMU_inacc: 0

