depth:
  abs:
    kp: 0.8
    ki: 0.0
    kd: 0.0
  rate:
    kp: 1.2
    ki: 0.0
    kd: 0.0

pitch:
  abs:
    kp: 5
    ki: 0.0
    kd: 0.0
  rate:
    kp: 5
    ki: 0.0
    kd: 0.0

roll:
  abs:
    kp: 0.8
    ki: 0.0
    kd: 0.0
  rate:
    kp: 1.2
    ki: 0.0
    kd: 0.0

yaw:
  abs:
    kp: 0.8
    ki: 0.0
    kd: 0.0
  rate:
    kp: 1.2
    ki: 0.0
    kd: 0.0